### PR TITLE
Base on alternative (freely distributable) Inspire Land Use version

### PR DESCRIPTION
**Pull request by ivorbosloper**

### CODE REVIEW

**Comment by m-mohr** [comment]
I'm just wondering, whether we should keep both versions of the data survey? Otherwise, LGTM.

**Review by m-mohr — APPROVED** [review]

**Comment by m-mohr** [comment]
Do you have privileges to merge yourself, by the way? Then I'd say merge yourself whenever you are ready :-)

**Comment by ivorbosloper** [comment]
> Do you have privileges to merge yourself, by the way? Then I'd say merge yourself whenever you are ready :-)

I don't have the access rights, would be handy.

**Comment by m-mohr** [comment]
I added you to a couple of repositories with maintain permissions, so you should be able to work more freely now. Let me know if there's any repository (e.g. any extension) that you'd like to work on and need permissions for.

At least for data-survey you don't really need to go through a PR process.  Leavig this open for you to test your new permissions ;-)

**Pull request merged**
